name: VueJS package

on: [push]

jobs:
  unit_test-lint:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - run: |
          npm install
          npm ci
          npm run build
          npm run test:unit
          npm run lint
